### ISSUE TITLE
The extends property is mapped when its value is null, making the MailOptions to throw an exception

### ISSUE THREAD

**Issue by vostrikov** [acelaya/ZF2-AcMailer#113]
Hi, version 5.0.1, I get an error 
An abstract factory could not create an instance of acmailer.mailservice.default(alias: AcMailer\Service\MailService)

**Comment by acelaya** [comment]
I'm going to need the whole exception trace and the previous exception in
order to know what's happening.
The error page should display that information.

--
Alejandro Celaya Alastrué

**Comment by vostrikov** [comment]
<h1>An error occurred</h1><h2>An error occurred during execution; please try again later.</h2><hr/><h2>Additional information:</h2><h3>Zend\ServiceManager\Exception\ServiceNotCreatedException</h3><dl><dt>File:</dt><dd><pre class="prettyprint linenums">/var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:1135</pre></dd><dt>Message:</dt><dd><pre class="prettyprint linenums">An abstract factory could not create an instance of acmailer.mailservice.default(alias: acmailer.mailservice.default).</pre></dd><dt>Stack trace:</dt><dd><pre class="prettyprint linenums">#0 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#1 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#2 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#3 /var/www/zacenoy/data/www/zacenoy.ru/module/Application/src/Application/Controller/CatalogController.php(275): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailse...&#039;)
#4 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Application\Controller\CatalogController-&gt;searchAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#7 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController-&gt;dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 [internal function]: Zend\Mvc\DispatchListener-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/zacenoy/data/www/zacenoy.ru/public/index.php(17): Zend\Mvc\Application-&gt;run()
#15 {main}</pre></dd></dl><hr/><h2>Previous exceptions:</h2><ul class="unstyled"><li><h3>Zend\ServiceManager\Exception\ServiceNotCreatedException</h3><dl><dt>File:</dt><dd><pre class="prettyprint linenums">/var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:946</pre></dd><dt>Message:</dt><dd><pre class="prettyprint linenums">An exception was raised while creating &quot;acmailer.mailservice.default&quot;; no instance returned</pre></dd><dt>Stack trace:</dt><dd><pre class="prettyprint linenums">#0 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1129): Zend\ServiceManager\ServiceManager-&gt;createServiceViaCallback(Array, &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#1 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#2 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#3 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#4 /var/www/zacenoy/data/www/zacenoy.ru/module/Application/src/Application/Controller/CatalogController.php(275): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailse...&#039;)
#5 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Application\Controller\CatalogController-&gt;searchAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController-&gt;dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/zacenoy/data/www/zacenoy.ru/public/index.php(17): Zend\Mvc\Application-&gt;run()
#16 {main}</pre></dd></dl></li><li><h3>Zend\ServiceManager\Exception\ServiceNotCreatedException</h3><dl><dt>File:</dt><dd><pre class="prettyprint linenums">/var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:1135</pre></dd><dt>Message:</dt><dd><pre class="prettyprint linenums">An abstract factory could not create an instance of acmailer.mailoptions.default(alias: acmailer.mailoptions.default).</pre></dd><dt>Stack trace:</dt><dd><pre class="prettyprint linenums">#0 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#1 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#2 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#3 /var/www/zacenoy/data/www/zacenoy.ru/vendor/acelaya/zf2-acmailer/src/Service/Factory/MailServiceAbstractFactory.php(49): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailop...&#039;)
#4 [internal function]: AcMailer\Service\Factory\MailServiceAbstractFactory-&gt;createServiceWithName(Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#5 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#6 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1129): Zend\ServiceManager\ServiceManager-&gt;createServiceViaCallback(Array, &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#7 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#8 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#9 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#10 /var/www/zacenoy/data/www/zacenoy.ru/module/Application/src/Application/Controller/CatalogController.php(275): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailse...&#039;)
#11 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Application\Controller\CatalogController-&gt;searchAction()
#12 [internal function]: Zend\Mvc\Controller\AbstractActionController-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController-&gt;dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 [internal function]: Zend\Mvc\DispatchListener-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/zacenoy/data/www/zacenoy.ru/public/index.php(17): Zend\Mvc\Application-&gt;run()
#22 {main}</pre></dd></dl></li><li><h3>Zend\ServiceManager\Exception\ServiceNotCreatedException</h3><dl><dt>File:</dt><dd><pre class="prettyprint linenums">/var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:946</pre></dd><dt>Message:</dt><dd><pre class="prettyprint linenums">An exception was raised while creating &quot;acmailer.mailoptions.default&quot;; no instance returned</pre></dd><dt>Stack trace:</dt><dd><pre class="prettyprint linenums">#0 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1129): Zend\ServiceManager\ServiceManager-&gt;createServiceViaCallback(Array, &#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#1 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#2 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#3 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#4 /var/www/zacenoy/data/www/zacenoy.ru/vendor/acelaya/zf2-acmailer/src/Service/Factory/MailServiceAbstractFactory.php(49): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailop...&#039;)
#5 [internal function]: AcMailer\Service\Factory\MailServiceAbstractFactory-&gt;createServiceWithName(Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#6 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#7 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1129): Zend\ServiceManager\ServiceManager-&gt;createServiceViaCallback(Array, &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#8 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#9 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#10 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#11 /var/www/zacenoy/data/www/zacenoy.ru/module/Application/src/Application/Controller/CatalogController.php(275): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailse...&#039;)
#12 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Application\Controller\CatalogController-&gt;searchAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController-&gt;dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /var/www/zacenoy/data/www/zacenoy.ru/public/index.php(17): Zend\Mvc\Application-&gt;run()
#23 {main}</pre></dd></dl></li><li><h3>Zend\Stdlib\Exception\BadMethodCallException</h3><dl><dt>File:</dt><dd><pre class="prettyprint linenums">/var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-stdlib/src/AbstractOptions.php:110</pre></dd><dt>Message:</dt><dd><pre class="prettyprint linenums">The option &quot;extends&quot; does not have a callable &quot;setExtends&quot; (&quot;setextends&quot;) setter method which must be defined</pre></dd><dt>Stack trace:</dt><dd><pre class="prettyprint linenums">#0 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-stdlib/src/AbstractOptions.php(62): Zend\Stdlib\AbstractOptions-&gt;__set(&#039;extends&#039;, NULL)
#1 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-stdlib/src/AbstractOptions.php(32): Zend\Stdlib\AbstractOptions-&gt;setFromArray(Array)
#2 /var/www/zacenoy/data/www/zacenoy.ru/vendor/acelaya/zf2-acmailer/src/Options/Factory/MailOptionsAbstractFactory.php(47): Zend\Stdlib\AbstractOptions-&gt;__construct(Array)
#3 [internal function]: AcMailer\Options\Factory\MailOptionsAbstractFactory-&gt;createServiceWithName(Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#4 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#5 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1129): Zend\ServiceManager\ServiceManager-&gt;createServiceViaCallback(Array, &#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#6 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#7 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailop...&#039;, &#039;acmailer.mailop...&#039;)
#8 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#9 /var/www/zacenoy/data/www/zacenoy.ru/vendor/acelaya/zf2-acmailer/src/Service/Factory/MailServiceAbstractFactory.php(49): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailop...&#039;)
#10 [internal function]: AcMailer\Service\Factory\MailServiceAbstractFactory-&gt;createServiceWithName(Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#11 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#12 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1129): Zend\ServiceManager\ServiceManager-&gt;createServiceViaCallback(Array, &#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#13 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(646): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#14 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager-&gt;doCreate(&#039;acmailer.mailse...&#039;, &#039;acmailer.mailse...&#039;)
#15 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager-&gt;create(Array)
#16 /var/www/zacenoy/data/www/zacenoy.ru/module/Application/src/Application/Controller/CatalogController.php(275): Zend\ServiceManager\ServiceManager-&gt;get(&#039;acmailer.mailse...&#039;)
#17 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Application\Controller\CatalogController-&gt;searchAction()
#18 [internal function]: Zend\Mvc\Controller\AbstractActionController-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController-&gt;dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 [internal function]: Zend\Mvc\DispatchListener-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#25 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /var/www/zacenoy/data/www/zacenoy.ru/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager-&gt;trigger(&#039;dispatch&#039;, Object(Zend\Mvc\MvcEvent), Object(Closure))
#27 /var/www/zacenoy/data/www/zacenoy.ru/public/index.php(17): Zend\Mvc\Application-&gt;run()
#28 {main}</pre></dd></dl></li></ul>

**Comment by acelaya** [comment]
Have you recently updated from version 4? I have seen other people having this problem while working with the old configuration which is not compatible. 
If that is your case, use the migration CLI tool

**Comment by vostrikov** [comment]
This my config mail.global.php

<pre><?php
return [
    'acmailer_options' => [

        'default' => [

            'extends' => null,

            'mail_adapter' => '\Zend\Mail\Transport\Sendmail',

            'transport' => '\Zend\Mail\Transport\Sendmail',

            'message_options' => [

                'from' => 'noreply@zacenoy.ru',

                'from_name' => 'Заценой',

                'body' => [
                    'content' => '',
                    'charset' => 'utf-8',
                    'use_template' => false,
                ],
            ],

            'smtp_options' => [
             
                'host' => '127.0.0.1',
          
                'port' => 25,

                'connection_class' => 'smtp',

                'connection_config' => [
               
                    'username' => 'noreply@zacenoy.ru',

                    'password' => '*********',

                    'ssl' => false,
                ],
            ],

            'file_options' => [
             
            ],

        ],

    ],
];</pre>

**Comment by acelaya** [comment]
Try removing the 'extends' option. It is supposed to work with it, but the error suggests that the problem comes from there. Since you are not using it, there shouldn't be any problem by removing it.
I'll check it later in case it is a bug.

**Comment by acelaya** [comment]
I'm also seeing that your configuration lacks the top-level `acmailer_options` config key. Are you sure you have it.

**Comment by vostrikov** [comment]
I can't get instance of service. 
An abstract factory could not create an instance of acmailer.mailservice.default(alias: AcMailer\Service\MailService).
Сonfig overwritten, acmailer_options exist

**Comment by acelaya** [comment]
Ok, let me try it with your configuration and see what happens.

--
Alejandro Celaya Alastrué

**Comment by vostrikov** [comment]
<pre><?php
return [
    'acmailer_options' => [

        'default' => [

            'extends' => null,

            'mail_adapter' => '\Zend\Mail\Transport\Sendmail',

            'transport' => '\Zend\Mail\Transport\Sendmail',

            'message_options' => [

                'from' => 'info@test.ru',

                'from_name' => 'test',

                'body' => [
                    'content' => '',
                    'charset' => 'utf-8',
                    'use_template' => false,
                ],
            ],

            'smtp_options' => [

                'host' => '127.0.0.1',

                'port' => 25,

                'connection_class' => 'smtp',

                'connection_config' => [

                    'username' => 'info@test.ru',

                    'password' => '********',

                    'ssl' => false,
                ],
            ],

            'file_options' => [
             
            ],

        ],

    ],
];</pre>

Composer "acelaya/zf2-acmailer": "~5.0"

**Comment by acelaya** [comment]
It is definitely a bug. If you set the property `extends` to `null`, it tries to map it into an Options object and fails since it is not defined.
It will work if you remove the `extends` property from your configuration. In the meantime I'll fix the problem.

Sorry I wasn't able to test it earlier. I've been really busy this week.

**Comment by acelaya** [comment]
It is now fixed as of v5.1.1 https://github.com/acelaya/ZF2-AcMailer/releases/tag/v5.1.1
Thanks for your time!
