### ISSUE TITLE
Working from localhost but not from live server

### ISSUE THREAD

**Issue by gioiafueter** [acelaya/ZF2-AcMailer#115]
From localhost I can send emails perfectly, but from the live server, I get the following error: I already tried adding a server name setting for the smtp configuration, and now I get the same error except of course now I get helo('mydomain')... Any idea what may be wrong?

#0 /srv/www/*****/Mail/Protocol/Smtp.php(177): Zend\Mail\Protocol\AbstractProtocol->_expect(220, 180)

#1 /srv/www*****/Mail/Transport/Smtp.php(376): Zend\Mail\Protocol\Smtp->helo('localhost')
#2 /srv/www/*****//Mail/Transport/Smtp.php(361): Zend\Mail\Transport\Smtp->connect()
#3 /srv/www/*****//Zend/Mail/Transport/Smtp.php(372): Zend\Mail\Transport\Smtp->lazyLoadConnection()
#4 /srv/www/*****//Mail/Transport/Smtp.php(229): Zend\Mail\Transport\Smtp->connect()
#5 /srv/www/*****/MailService.php(95): Zend\Mail\Transport\Smtp->send(Object(Zend\Mail\Message))
#6 /srv/www/*****/module/Mail/src/Mail/Controller/MailController.php(57): AcMailer\Service\Mai lService->send()
#7/srv/www/*****/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): Mail\Controller\MailController->sendMailAction()
#8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /srv/www*****/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /srv/www/*****/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /srv/www/*****/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /srv/www/*****/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /srv/www/*****/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /srv/www/*****/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /srv/www/*****/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /srv/www/*****/public/index.php(42): Zend\Mvc\Application->run()
#18 {main}

**Comment by acelaya** [comment]
I would need to see the exception message, not just the stack trace

**Comment by gioiafueter** [comment]
Sorry, the exception message is empty:
An error occurred. Exception: \n#0 /srv/www/adex.is/htdocs/live/vendor/zendframework/zendframework/library/Zend/Mail/Protocol/Smtp.php(177): Zend\Mail\Protocol\AbstractProtocol->_expect(220, 180)

**Comment by acelaya** [comment]
It's a little weird that there is no exception message.
You will have to check some things for me.
* Make sure you can send emails by using the same configuration by other means
* Make sure you are using the proper AcMailer version. The configuration has changed in v5, maybe you are using an outdated config file.

If all fails, please, paste your configuration here so I can review it (do not paste any password)

**Comment by acelaya** [comment]
I'm closing this because of the lack of activity
