### ISSUE TITLE
Update to ZF3 components

### ISSUE THREAD

**Issue by acelaya** [acelaya/ZF2-AcMailer#124]

**Comment by Rockstar04** [comment]
ZF3 has been officially released: https://framework.zend.com/blog/2016-06-28-zend-framework-3.html

**Comment by acelaya** [comment]
Yes, I know. It's been a while since I wanted to support ZF3 components.
Any help is welcome :)

--
Alejandro Celaya Alastrué

**Comment by Rockstar04** [comment]
Do you know what parts of the library need to be updated?

**Comment by acelaya** [comment]
I'm already working on the update.
I'll have it published in a couple days

--
Alejandro Celaya Alastrué

**Comment by Rockstar04** [comment]
Awesome! Thanks for your ongoing support of this library!

**Comment by Estigy** [comment]
Thanks, waiting for it too :-)

**Comment by acelaya** [comment]
There's a complex system of abstract factories in this module, so I don't
think I can support ServiceManager 2 and 3 at the same time.
I'll publish v6 of this module supporting ZF3, and keep v5 for ZF2.

The other thing is that the name of the module includes the keyword ZF2.
That wasn't probably a good decision.
Renaming the repo would be easy, but I don't see an easy way to change the
composer package name.

By the moment I'll keep the name

--
Alejandro Celaya Alastrué

**Comment by acelaya** [comment]
Just pushed v6.0.0 of this module, supporting ZF3 components.
I have also updated minimum PHP version to 5.6

**Comment by Rockstar04** [comment]
Thanks for the quick update!
