### ISSUE TITLE
false is unsupported SSL type

### ISSUE THREAD

**Issue by marinovdf** [acelaya/ZF2-AcMailer#125]
I have two mail config in my app (`mail.local.php`, `mail.global.php`).
`mail.global.php` is config with real SMTP settings and supported SSL (`ssl => 'tls'`).
`mail.local.php` is dev config with fake SMTP setting (mailcatcher).

When I set up `ssl => false` in `mail.local.php` then app throw an exception ` is unsupported SSL type`.
But I see comment in config:
```
/*
 * This defines the encryption type to be used, 'ssl' or 'tls'.
 * Boolean false should be used to disable SSL.
 *
 * Default value is false
 */
```

What am I doing wrong?

**Comment by acelaya** [comment]
What's the Zend/Mail version you are working with?

--
Alejandro Celaya Alastrué

**Comment by marinovdf** [comment]
My Zend\Mail version is 2.7.1

**Comment by acelaya** [comment]
The default value used to be false, but maybe that has changed in latest versions. I'll take a look at it.

**Comment by marinovdf** [comment]
OK, thanks

**Comment by marinovdf** [comment]
Hi @acelaya . Did you have any solution?

**Comment by acelaya** [comment]
I'm a little busy this weekend. I'll check it next one. 
However, that value is the one used by the SmtpOptions object, so, by the moment, you could read the documentation for v2.7 and see what's the default value now. Maybe it's null.

**Comment by marinovdf** [comment]
OK. I'll see

**Comment by acelaya** [comment]
I have checked this, and it will ignore ssl if you set it with value `null`. Apparently it always failed with false, but no one ever complained.
I'll push a patch version fixing documentation and default value.

**Comment by marinovdf** [comment]
Thanks. It works.
