### ISSUE TITLE
Cannot configure gmail

### ISSUE THREAD

**Issue by bartoszzajac** [acelaya/ZF2-AcMailer#131]
I'm getting this message from gmail:
5.5.1 Authentication Required. Learn more at 5.5.1  https://support.google.com/mail/?p=WantAuthError
I enables access for less secured apps in gmail.
My config is: http://pastebin.com/fnup7W8j

In debug I can see that in SMTP.php $this->transport is 'tcp' - shouldn't be 'tls' ?

**Comment by acelaya** [comment]
For gmail, the `connection_class` property has to be "login", not "smtp"

**Comment by bartoszzajac** [comment]
Now that's a quick response!
Works.
Thanks!

**Comment by acelaya** [comment]
I'm glad that it works. I'm closing this then.
