### ISSUE TITLE
UTF-8 problems when sending email with attachments

### ISSUE THREAD

**Issue by gmusteata** [acelaya/ZF2-AcMailer#65]
Hi,

I'm having a charset issue when sending an email with attachments.
What I have noticed in **MailService**, in the **attachFiles** method, is that a new **MimePart** object is created, and the charset is not set anymore:

	$bodyContent        = $mimeMessage->generateMessage();
    $bodyPart           = new MimePart($bodyContent);
    $bodyPart->type     = Mime::TYPE_HTML; // TODO

This is generating a body part without the charset specified.

In case the email doesn't have attachments, there are no body parts, and the main charset is being used.

Setting the charset in the attachFiles method did the trick for me:

	$bodyPart->charset  = "utf-8";

If you agree that this is indeed an issue, would it be possible to make a quick fix?

Thanks,
Gabriel

**Comment by acelaya** [comment]
Just fixed this bug, but I will tag it in v4.5.0. Until then you can point to the last commit in develop by running `composer require acelaya/zf2-acmailer:dev-develop#314098076e5026ed9c693836208720b1a123ac99`.
