### ISSUE TITLE
Allow to register multiple mail services, each one consuming its own configuration

### ISSUE THREAD

**Issue by acelaya** [acelaya/ZF2-AcMailer#66]
Similar to what is done with EntityManagers in DoctrineORMModule.

- [x] Create an abstract factory for the MailService
- [x] Create an abstract factory for the MailOptions
- [x] Create an abstract factory for the controller plugin
- [x] Define tests covering new elements

**Comment by acelaya** [comment]
Will break BC. I'm going to plan this for v5.0.0

**Comment by marceltk** [comment]
I solved with in previous version  "$message->setHeaders(new \Zend\Mail\Headers);"
Send mail in foreach();

**Comment by acelaya** [comment]
I don't think that has nothing to do with what I meant to say with this issue. 

In current stable version, there is only one mail service. I plan to add an abstract factory that is able to create multiple services, each one of them consuming a different configuration block.

**Comment by marceltk** [comment]
ahh ok!.
set $message->setHeaders(new \Zend\Mail\Headers); 
in my application, is remove all headers, after set default from is null configuration (acmailer.config.php), cause problem in send mail on each interaction afetr first. (php foreach)
My question is another fix or bug.
I'm sorry, another issue.

**Comment by acelaya** [comment]
Don't worry ;)

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com
