### ISSUE TITLE
Send mail to gmail

### ISSUE THREAD

**Issue by marceltk** [acelaya/ZF2-AcMailer#76]
How to send image embedded in email?
has possibilty?

**Comment by acelaya** [comment]
Of course! 

You have to attach the images to the message and set the images like this. 

```html
<img src="id:attached-image-name.jpg">
```

That's it.

**Comment by marceltk** [comment]
Perfect! 
Tks!

**Comment by marceltk** [comment]
With id:imagem.jpg not working
Wtih cid:imagem.jpg is working, only gmail server.

Tks!

**Comment by acelaya** [comment]
Right, my bad. It's "cid", not "id"

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by marceltk** [comment]
Good!
run in gmail, not run in others mail clients.
no problems! 
Tks!
