### ISSUE TITLE
base64 files

### ISSUE THREAD

**Issue by FraGoTe** [acelaya/ZF2-AcMailer#88]
How to attach base64 files?

**Comment by acelaya** [comment]
The MailService API allows you to attach files from disk locations.
If you need to attach a file that is already a base64 string, you will need to add a Mime\Part to the body of the email.
This is internally done by the mail service, so you can take a look at [the code](https://github.com/acelaya/ZF2-AcMailer/blob/master/src/Service/MailService.php#L225) if you need to do it by yourself.

**Comment by FraGoTe** [comment]
Finally I did it in this way:

```PHP
foreach ($docAdj as $docName => $docBase64) {
                $outputPath = tempnam(realpath("tmp"), $docName . '.pdf');  //generate unique temp file name    
                chmod($outputPath, 0766);
                $handle = fopen($outputPath, 'a');
                fwrite($handle, base64_decode($docBase64));
                $mailService->addAttachment($outputPath, $docName);
                fclose($handle);
 }
```

**Comment by acelaya** [comment]
Good! Thanks for posting your approach.
