### ISSUE TITLE
Deleting attachement fails after email is sent

### ISSUE THREAD

**Issue by tad3j** [acelaya/ZF2-AcMailer#93]
When I send an email I want to delete the files if email was sent (->isValid()), but I'm getting a PHP Warning when trying to do so:

    Warning:  unlink(./data/tmp/file.txt): Permission denied

I get this exception in Windows so there shouldn't be any permissions problems; it looks like to me that this module locks the attachments.

**Comment by acelaya** [comment]
Thanks. I'll take a look.

**Comment by acelaya** [comment]
I couldn't reproduce this. Can you elaborate?
Are you able to delete the file before sending the email? And before even attaching it?
What version of ZF and PHP are you using?

**Comment by tad3j** [comment]
I've noticed that I only get that PHP warning on Windows, it works OK on Linux...maybe that's why.
Yes, I'm able to delete it before and after, it just looks it's locked when I try to delete from inside the code.

I'm using ZF 2.4.2 and PHP 5.4.16.

**Comment by acelaya** [comment]
I'll try to test it in a Windows environment.
