### ISSUE TITLE
After updating to ZF 2.4.2 module throws the exception on try to get service from servicemanager.

### ISSUE THREAD

**Issue by Syberon** [acelaya/ZF2-AcMailer#94]
After updating to ZF 2.4.2 module throws the exception on try to get service from servicemanager.

$mailService = $this->getServiceLocator()->get('AcMailer\Service\MailService');

Uncaught exception 'Zend\Mail\Exception\InvalidArgumentException' with message 'Email must be a valid email address'

The issue is related to parameter "from' => ''" in config file. New version of zend framework not allow to pass empty From header on module init. If i uncomment this parameter and fill it with something all works fine, but i don't need this default parameter because i set "from" header in runtime.

**Comment by acelaya** [comment]
Thank you! I'll fix it as soon as possible.

**Comment by EvKoh** [comment]
I have same problem with ZF 2.3.*

**Comment by alejandro-fiore** [comment]
The problem arise when no "from" config exists in $config["mail_options"]["from"].
A quick workaround is to set the from option in mail.global.php file inside config/autoload/
I suppose that Zend change something in Mail clasess and doesn´t accept empty "from" address.

**Comment by acelaya** [comment]
That seems to be the problem. I will try to fix it this weekend, but any
pull request is very welcome ;)
Thank you all for reporting the issue

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by alejandro-fiore** [comment]
I already sent you a pull request!
https://github.com/acelaya/ZF2-AcMailer/pull/96

Thanks for sharing your work!

**Comment by acelaya** [comment]
I've seen it, thanks!

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by acelaya** [comment]
The pull request won't be merged, since there are some BC breaks in ZF2.4 that cannot be applied in this module without introducing a BC break on itself.
I will push a small version 4.5.1 that will require ZF2.2 or 2.3.
The upcomming version 5 (which is already introducing other BC breaks) will support ZF2.4.

By the moment, keep using the workaround of defining a from addresses at configuration level.

**Comment by acelaya** [comment]
I'm glad to say that finally found a workaround so that I can fix the problems with ZF2.4 without introducing a BC break.
Version [4.5.1](https://github.com/acelaya/ZF2-AcMailer/releases/tag/v4.5.1) is available now.

**Comment by alejandro-fiore** [comment]
¡Gracias Alejandro! 
Thanks @acelaya for the fix!
